sudo: true
dist: trusty
language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
addons:
  firefox: latest
  chrome: stable
install: yarn
before_script:
  - gulp lint
  - xvfb-run -s '-screen 0 1024x768x24' wct
script:
  - 'if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then xvfb-run -s ''-screen 0 1024x768x24'' wct --module-resolution=node --npm --env saucelabs; fi'
  - 'if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then xvfb-run -s ''-screen 0 1024x768x24'' wct --module-resolution=node --npm --env saucelabs-cron; fi'
notifications:
  email:
    on_success: never

